name: terraform plan
on: pull_request

jobs:
  plan:
    name: plan
    runs-on: ubuntu-latest
    steps:
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
      - name: checkout
        uses: actions/checkout@v3
      - uses: aws-action/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:<account-id>:role/bursting-mackerel-dev-gha
          role-session-name: gha-tf-plan
          aws-region: us-east-1
      - name: run terraform plan
        run: |
          terraform init
          terraform plan